# Auto-generated by cmake/git_version.cmake — do not edit.
# Include this file to get version variables in cmake scripts.

set(VERSION_MAJOR    "@VERSION_MAJOR@")
set(VERSION_MINOR    "@VERSION_MINOR@")
set(VERSION_PATCH    "@VERSION_PATCH@")
set(VERSION_DIRTY    "@GIT_DIRTY@")
set(VERSION_STRING   "@VERSION_STRING@")
set(VERSION_FULL     "@VERSION_FULL@")
set(GIT_HASH         "@GIT_HASH@")
set(COMPILER_VERSION "@COMPILER_VERSION@")
set(BUILD_USER       "@BUILD_USER@")
set(HOST_OS          "@HOST_OS@")

# Convenience for CPack
set(CPACK_PACKAGE_VERSION_MAJOR "@VERSION_MAJOR@")
set(CPACK_PACKAGE_VERSION_MINOR "@VERSION_MINOR@")
set(CPACK_PACKAGE_VERSION_PATCH "@VERSION_PATCH@")
set(CPACK_PACKAGE_VERSION       "@VERSION_STRING@")
