#pragma once

// Auto-generated by cmake/git_version.cmake — do not edit.

#include <string_view>

namespace BuildInfo {

constexpr int versionMajor = @VERSION_MAJOR@;
constexpr int versionMinor = @VERSION_MINOR@;
constexpr int versionPatch = @VERSION_PATCH@;
constexpr bool versionDirty = (@GIT_DIRTY@ != 0);

constexpr std::string_view versionString   = "@VERSION_STRING@";
constexpr std::string_view versionFull     = "@VERSION_FULL@";
constexpr std::string_view gitHash         = "@GIT_HASH@";

constexpr std::string_view compilerVersion = "@COMPILER_VERSION@";
constexpr std::string_view buildUser       = "@BUILD_USER@";
constexpr std::string_view hostOs          = "@HOST_OS@";

} // namespace BuildInfo
